version: "3.8"
services:
  customer-service:
    build: .
    image: customer-service-image
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - customerdb
  customerdb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: techsingou123
      MYSQL_DATABASE: customer-db
      MYSQL_USER: techsingou
      MYSQL_PASSWORD: techsingou123



